# Generated by Django 5.2.4 on 2025-07-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile_facebook_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='instagram_username',
            new_name='instagram_business_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_handle',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
