# Generated by Django 5.2.4 on 2025-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_instagram_username_userprofile_instagram_business_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_page_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
