# Generated by Django 5.2.4 on 2025-07-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile_facebook_page_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_access_token',
        ),
    ]
